server:
  port: 8082
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      lifecycle-management: start_only
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE