CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    rating INT NOT NULL,
    content VARCHAR(500)
);

INSERT INTO reviews (product_id, rating, content) VALUES
(1, 5, 'Tot'), (1, 4, 'Ok'),
(2, 5, 'Me Iphone'), (2, 3, 'Hoi dat'), (2, 4, 'On');