CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE ,
    url TEXT NOT NULL
);

CREATE INDEX idx_product_images_product_id ON product_images(product_id);

INSERT INTO product_images (product_id, url) VALUES
                                                 (1, 'https://cdn.example.com/p1-front.jpg'),
                                                 (1, 'https://cdn.example.com/p1-back.jpg'),
                                                 (2, 'https://cdn.example.com/p2-1.jpg'),
                                                 (2, 'https://cdn.example.com/p2-2.jpg'),
                                                 (2, 'https://cdn.example.com/p2-3.jpg');